apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  serviceSubnet: "10.96.0.0/20" # until 10.96.15.255
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6444
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  # extraPortMappings:
  # - containerPort: 30000
  #   hostPort: 1053
  #   listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
  #   protocol: udp # Optional, defaults to tcp
  # - containerPort: 30000
  #   hostPort: 1053
  #   listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
  #   protocol: tcp # Optional, defaults to tcp
