apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: examplednsrecordcname
spec:
  endpoints:
  - dnsName: cname.5gc.3gppnetwork.org
    recordTTL: 180
    recordType: CNAME
    targets:
    - nginx.5gc.3gppnetwork.org
