apiVersion: v1
kind: Service
metadata:
  name: coredns-ext-service
  namespace: dns
  annotations: 
    external-dns.alpha.kubernetes.io/hostname: coredns.5gc.3gppnetwork.org.
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: coredns
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53
      name: upd-dns
    - protocol: TCP
      port: 53
      targetPort: 53
      name: tcp-dns
