apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
  labels:
    app: curl
spec:
  containers:
  - name: curl-container
    image: curlimages/curl:latest
    command: ['/bin/sh', '-c', '--']
    args: ['while true; do echo "Running Bash in a loop..."; sleep 10; done']
