kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: dnsendpoint-read
rules:
- apiGroups: ["externaldns.k8s.io"]
  resources: ["dnsendpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["externaldns.k8s.io"]
  resources: ["dnsendpoints/status"]
  verbs: ["update"]
