---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pdns-init-script-cm.yaml
  - pdns-deploy.yaml
  - pdns-svc.yaml
  - coredns-ext-svc.yaml

configMapGenerator:
  - name: mariadb-values
    files:
      - values.yaml=./mariadb-values.yaml
  # - name: external-dns-values
  #   namespace: telco-dns
  #   files:
  #     - values.yaml=./external-dns-values.yaml
  # - name: core-dns-values
  #   namespace: telco-dns
  #   files:
  #     - values.yaml=./core-dns-values.yaml
