---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pdns-init-script-cm.yaml
  - pdns-deploy.yaml
  - pdns-svc.yaml
  - coredns-ext-svc.yaml
  - dnsutils-pod.yaml
  - kube-system-coredns-cm.yaml
  - dnsendpoint-read-role.yaml
