---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pdns-init-script-cm.yaml
  - pdns-deploy.yaml
  - pdns-svc.yaml
  - coredns-ext-svc.yaml
  - curl-pod.yaml
  - kube-system-coredns-cm.yaml
