apiVersion: v1
kind: Service
metadata:
  name: pdns-service
  annotations: 
    external-dns.alpha.kubernetes.io/internal-hostname: pdns-int.5gc.3gppnetwork.org.
spec:
  selector:
    app: pdns
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: api
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
  type: ClusterIP
  clusterIP: 10.96.0.12
---
apiVersion: v1
kind: Service
metadata:
  name: pdns-ext-service
  annotations: 
    external-dns.alpha.kubernetes.io/hostname: pdns-ext.5gc.3gppnetwork.org.
spec:
  selector:
    app: pdns
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: api
      nodePort: 30004
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
      nodePort: 30003
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
      nodePort: 30003
  type: NodePort
