---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  namespace: metallb-system
  name: output-l2-advertisement
spec:
  ipAddressPools:
  - output-ipaddresspool
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: output-ipaddresspool
  namespace: metallb-system
spec:
  addresses:
    - 172.18.2.0/24
 